In [ ]:
# Q1

In [47]:
from functools import reduce

A = ([[4, -4],
      [-7, 3]])

print("A: ")

A: 


In [48]:
for i in A:
  print(i)


[4, -4]
[-7, 3]


In [49]:
I = ([[1, 0],
      [0, 1]])

print("I:")

I:


In [50]:
for m in I:
  print(m)

[1, 0]
[0, 1]


In [51]:
AxI = ([[0, 0],
        [0, 0]])

for i in range(len(A)):
    for j in range(len(I[0])):
        for k in range(len(I)):
            AxI[i][j] += A[i][k] * I[k][j]

print("\nAxI:")


AxI:


In [52]:
for m in AxI:
    print(AxI)

[[4, -4], [-7, 3]]
[[4, -4], [-7, 3]]


In [53]:
print("nFactor:")

nFactor:


In [54]:
lamda = ([[0,0],
        [0,0]])

for i in range(len(AxI)):
    for j in range(len(AxI)):
     #factor[i][j] = AxI[i][j]
     lamda[i][i] = ("x".format(AxI[i][i]))

print('\n= ({0} - {1})({2} - {3}) - ({4})({5})=0'.format(AxI[0][0], lamda[0][0], AxI[1][1], lamda[1][1], AxI[1][0], AxI[0][1]))


= (4 - x)(3 - x) - (-7)(-4)=0


In [55]:
count_id = 0 # number of id
coeff = 0 # coefficient
for i in range(len(lamda)):
    for j in range(len(lamda)):
            if (lamda[i][j] == "x"):
                count_id = count_id + 1
                coeff = ("x^{0}".format(count_id))
               
       
print("\n= {0}{1}{2}+{3} - {4} = 0".format(coeff, -AxI[0][0]-AxI[1][1], lamda[1][1], (-AxI[0][0])*(-AxI[1][1]), (-AxI[1][0]) * (-AxI[0][1])))        


= x^2-7x+12 - 28 = 0


In [56]:
factor1 = (-AxI[0][0] - AxI[1][1])

determinant = (((-AxI[0][0])*(-AxI[1][1]))-((-AxI[1][0]) * (-AxI[0][1])))

factor1 = determinant - factor1

print(factor1)

-9


In [57]:
print(determinant)

-16


In [58]:
print("Eigen Values:")

Eigen Values:


In [59]:
print("(x + ({0}))(x + ({1}))".format(factor1,determinant))

(x + (-9))(x + (-16))


In [60]:
print("Eigen Vector")

Eigen Vector


In [61]:
eval1 = AxI[0][0] - (factor1)
eval2 = AxI[1][1] - (factor1)

print(eval1, ",",eval2)

13 , 12


In [62]:
eiganVector1 = AxI[0][1] / eval2

eiganVector2 = AxI[1][0] / eval2

print("Eigan vectors are: {0} and {1}".format(eiganVector1, eiganVector2))


Eigan vectors are: -0.3333333333333333 and -0.5833333333333334


In [ ]:
# Q2

In [25]:
import numpy as np
a = np.array([[1, 0, 0, 3], [0, 0, 4, 0], [0, 0, 0, 0]])
print("Main array:")
print(a)
U, s, V = np.linalg.svd(a, full_matrices=False) # When a is a 2D array, and full_matrices=False, then it is factorized as u @ np.diag(s) @ vh = (u * s) @ vh
q, r = np.linalg.qr(a) #Factor the matrix a as qr, where q is orthonormal and r is upper-triangular.
print("factor of a given array by Singular Value Decomposition are: ")
print("U=\n", U, "\ns=\n", s, "\nV=\n", V)

Main array:
[[1 0 0 3]
 [0 0 4 0]
 [0 0 0 0]]
factor of a given array by Singular Value Decomposition are: 
U=
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] 
s=
 [4.         3.16227766 0.        ] 
V=
 [[-0.          0.          1.          0.        ]
 [ 0.31622777  0.          0.          0.9486833 ]
 [ 0.         -1.          0.          0.        ]]


In [ ]:
# Q3

In [27]:
import numpy as np
a = np.array([[1,1],[2,9]])
print("Main array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the array:")
print(result)

Main array:
[[1 1]
 [2 9]]
Determinant of the array:
7.000000000000001
